
// This file is generated automatically by vite.config.ts
// Do not edit this file manually

const Env = {
  "VITE_APP_ENV": "development",
  "VITE_API_URL": "http://localhost:3030/api",
  "VITE_VAR_NUMBER": 123,
  "VITE_VAR_BOOL": true,
  "VITE_APP_GOOGLE_MAP_KEY": "AIzaSyA51frSkC9NZaEWJxq8n6UGBPcbnnOLXsQ"
} as const;

export default Env;
